const Hobbies = [
    { code: 1, label: "Reading" },
    { code: 2, label: "Cooking" },
    { code: 3, label: "Traveling" },
    { code: 4, label: "Gardening" },
    { code: 5, label: "Photography" },
    { code: 6, label: "Gaming" },
    { code: 7, label: "Hiking" },
    { code: 8, label: "Painting" },
    { code: 9, label: "Fishing" },
    { code: 10, label: "Writing" },
    { code: 11, label: "Singing" },
    { code: 12, label: "Dancing" },
    { code: 13, label: "Yoga" },
    { code: 14, label: "Running" },
    { code: 15, label: "Cycling" },
    { code: 16, label: "Knitting" },
    { code: 17, label: "Birdwatching" },
    { code: 18, label: "Chess" },
    { code: 19, label: "Playing musical instruments" },
    { code: 20, label: "Swimming" },
    { code: 21, label: "Skydiving" },
    { code: 22, label: "Surfing" },
    { code: 23, label: "Scuba diving" },
    { code: 24, label: "Meditation" },
    { code: 25, label: "Volunteering" },
    { code: 26, label: "Cooking" },
    { code: 27, label: "Origami" },
    { code: 28, label: "Rock climbing" },
    { code: 29, label: "Bowling" },
    { code: 30, label: "Archery" },
    // Add more hobbies as needed
  ];
  export default Hobbies